config/routes.rb
Rails.application.routes.draw do
# orderlistコントローラ
    get 'order/top' => 'orderlist#top_page'

    get 'order/set_menu' => 'orderlist#set_menu'
    get 'order/alacarte_menu' => 'orderlist#alacarte'
    get 'order/noodle_menu' => 'orderlist#noodle'
    get 'order/rice_menu' => 'orderlist#rice'
    get 'order/drink_menu' => 'orderlist#drink'
    get 'order/dessert_menu' => 'orderlist#dessert'
    get 'order/recommend_menu' => 'orderlist#recommend'
    get 'order/search' => 'orderlist#search'
    
    get 'order/pre_order/:id' => 'orderlist#pre_order'
    post 'order/pre_order/:id' => 'orderlist#post_order'
    get 'order/ordered/:id' => 'orderlist#ordered'

    get 'order/modal_test/:id' => 'orderlist#modal', as: 'order_indiv'
    post 'order/modal_order' => 'orderlist#order_create'
    
end

app/models/orderlist.rb
class Orderlist < ApplicationRecord
end

app/controllers/orderlist_controller.rb
class OrderlistController < ApplicationController
    def top_page
    end
    
    def set_menu
        @menus1 = Menu.where(category: 11)
        @menus2 = Menu.where(category: 12)
        @menus3 = Menu.where(category: 13)

        # モーダルに表示させるとき
        # @orderlist = Orderlist.new
        # @menu = Menu.new

        # if params[:id] then
        #     # パラムズのidにあったメニューを取り出す
        #     @menu = Menu.find(params[:id])
        #     # 各オプションの中にものがあるかどうか
        #     # あったら変数に渡す
        #     if @menu.option1 then
        #         number = @menu.option1
        #         @option1 = Optiontable.find(number)
        #         @option_name1 = @option1.name_opt
        #     end
        #     if @menu.option2 then
        #         number = @menu.option2
        #         @option2 = Optiontable.find(number)
        #         @option_name2 = @option2.name_opt
    
        #     end
        #     if @menu.option3 then
        #         number = @menu.option3
        #         @option3 = Optiontable.find(number)
        #         @option_name3 = @option3.name_opt
        #     end
        # end
    end
    
    def alacarte
        @menus1 = Menu.where(category: 21)
        @menus2 = Menu.where(category: 22)
        @menus3 = Menu.where(category: 23)

    end
    
    def modal
        # パラムズのidにあったメニューを取り出す
        @menu = Menu.find(params[:id])
        @orderlist = Orderlist.new
        # 各オプションの中にものがあるかどうか
        # あったら変数に渡す
        if @menu.option1 then
            number = @menu.option1
            @option1 = Optiontable.find(number)
            @option_name1 = @option1.name_opt
        end
        if @menu.option2 then
            number = @menu.option2
            @option2 = Optiontable.find(number)
            @option_name2 = @option2.name_opt

        end
        if @menu.option3 then
            number = @menu.option3
            @option3 = Optiontable.find(number)
            @option_name3 = @option3.name_opt
        end
        
        respond_to do |format|
            format.html
            format.js
        end
    end
    
    def order_create
        # binding.pry
        # メニュー価格の呼び出し
        menu = Menu.find(orderlist_params[:menu_id])
        menu_price = menu.price

        # まだフォームを作ってない、とりあえずどんなパラムズになるかなって書いてみた。190117

        if orderlist_params[:option_id] then
            # オプション価格の呼び出し
            option = Optiontable.find(orderlist_params[:option_id])
            option_price = option.price_opt

            Orderlist.create(menu_id: orderlist_params[:menu_id], price: menu_price, number: orderlist_params[:number], state: "0")
            Orderlist.create(option_id: orderlist_params[:option_id], price: option_price, number: orderlist_params[:number], state: "0")

            # Orderlist.save(user_id: current_user.id, menu_id: params[:id], price: menu_price, number: orderlist_params[:number], state: 0)
            # Orderlist.save(user_id: current_user.id, option_id: orderlist_params[:option], price: option_price, number: orderlist_params[:number], state: 0)
        else

            # Orderlist.save(user_id: current_user.id, menu_id: params[:id], price: orderlist_params[:price], number: orderlist_params[:number], status: 0)
            Orderlist.create(menu_id: orderlist_params[:menu_id], price: orderlist_params[:price], number: orderlist_params[:number], state: "0")
        end
    end

private
    def orderlist_params
        params.require(:orderlist).permit(:number, :option_id, :menu_id)
    end
end

app/helpers/orderlist_helper.rb
module OrderlistHelper
end

app/views/orderlist/alacarte.html.erb
<div class="menu_background-color">
    <div class="menu_background">
        <header class="menu_header clearfix">
            <div class="menu_header_left">
                <div class="menu_button orange">
                    <a href="/order/top">
                        <p>トップへ</p>
                    </a>
                </div>
            </div>
            <div class="menu_button_right">
                <div class="menu_button orange">
                    <a href="#">
                        <p>会計</p>
                    </a>
                </div>
                <div class="menu_button orange">
                    <a href="#">
                        <p>呼出</p>
                    </a>
                </div>
                <div class="menu_button orange">
                    <a href="#">
                        <p>未注文</p>
                    </a>
                </div>
                <div class="menu_button orange">
                    <a href="#">
                        <p>注文済</p>
                    </a>
                </div>
            </div>
        </header>
        <div class="menu_category">
                <div class="menu_button orange">
                    <a href="#">
                        <p>セット</p>
                    </a>
                </div>
                <div class="menu_button">
                    <a href="/order/alacarte_menu">
                        <p>一品料理</p>
                    </a>
                </div>
                <div class="menu_button">
                    <a href="/order/noodle_menu">
                        <p>麺類</p>
                    </a>
                </div>
                <div class="menu_button">
                    <a href="/order/rice_menu">
                        <p>ご飯類</p>
                    </a>
                </div>
                <div class="menu_button">
                    <a href="/order/dessert_menu">
                        <p>デザート</p>
                    </a>
                </div>
                <div class="menu_button">
                    <a href="/order/drink_menu">
                        <p>ドリンク</p>
                    </a>
                </div>
        </div>
        <div class="line">
            <h2></h2>
        </div>
        <!--セットメニューに関わる部分-->
        <div class="menu_category2">
            <ul>
                <li id="category11" class="selected">
                    <p>ボリューム</p>
                </li>
                <li id="category12">
                    <p class="double">ランチ・<br>おすすめ</p>
                </li>
                <li id="category13">
                    <p>ユニーク</p>
                </li>
            </ul>
        </div>
        <div class="menu_indiv clearfix">
            <div class="category11">
                <% @menus1.each do |menu| %>
                    <div class="menu_indiv_block">
                        <div class="menu_indiv_block2">
                            <%= link_to (order_indiv_url(menu.id)) do %>
                                <img src=<%= menu.image %> alt="">
                                <div class="menu_indiv_name">
                                    <%= menu.name %>
                                </div>
                            <%end%>
                        </div>
                    </div>
                <% end %>
            </div>
            <div class="category12">
                <% @menus2.each do |menu| %>
                    <div class="menu_indiv_block">
                        <%= link_to (order_indiv_url(menu.id)) do %>
                            <div class="menu_indiv_block2">
                                <img src=<%= menu.image %> alt="">
                                <div class="menu_indiv_name">
                                    <%= menu.name %>
                                </div>
                            </div>
                        <%end%>                            
                    </div>
                <% end %>
            </div>
            <div class="category13">
                <% @menus3.each do |menu| %>
                    <div class="menu_indiv_block">
                        <%= link_to (order_indiv_url(menu.id)) do %>
                            <div class="menu_indiv_block2">
                                <img src=<%= menu.image %> alt="">
                                <div class="menu_indiv_name">
                                    <%= menu.name %>
                                </div>
                            </div>
                        <%end%>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/orderlist/modal.html.erb
<div id="modal_bg">
</div>

<div id="modal_menu_indiv">
    <!--<2% form_with url: users_path do |form| %>-->
    <%= form_for(@orderlist, url: '/order/modal_order') do |f| %>
    <%= f.hidden_field(:menu_id, value: @menu.id)%>
    
    <!--ラジオボタンを使って:menu_idを持たせている部分-->
    <%# f.radio_button(:menu_id, @menu.id, value: @menu.id, :checked => true) %>

    <div class="modal_menu_indiv_upper">
        <div class="modal_menu_image">
            <img src="<%= @menu.image %>" alt="">
            <div class="modal_menu_title_n_price clearfix">
                <div class="modal_menu_title">
                    <p><%= @menu.name %></p>
                </div>
                <div class="modal_menu_price">
                    <p><%= @menu.price %>円</p>
                </div>
            </div>
        </div>
        <div class="modal_menu_detail_n_number">
            <div class="modal_menu_detail">
                <p><%= @menu.detail %></p>
            </div>
            <div class="modal_menu_number_box clearfix">
                <div class="modal_menu_number">
                    <!--<p>1</p>-->
                    <%= f.radio_button(:number, 1, :checked => true) %>
                    <p><%= f.label(:number, "1", value: "1")  %></p>
                </div>
                <div class="modal_menu_number">
                    <!--<p>2</p>-->
                    <%= f.radio_button(:number, 2)%>
                    <p><%= f.label(:number, "2", value: "2")  %></p>
                </div>
                <div class="modal_menu_number">
                    <!--<p>3</p>-->
                    <%= f.radio_button(:number, 3) %>
                    <p><%= f.label(:number, "3", value: "3")  %></p>
                </div>
                <div class="modal_menu_number">
                    <!--<p>4</p>-->
                    <%= f.radio_button(:number, 4) %>
                    <p><%= f.label(:number, "4", value: "4")  %></p>
                </div>
            </div>
        </div>
    </div>
    <div class="modal_menu_indiv_bottom">
        <div class="modal_menu_option_box">
            <!--もしオプションの中に番号があったら表示-->
            <% if @option1 %>
                <div class="modal_menu_option">
                    <%= f.radio_button(:option_id, @option1.id) %>
                    <p><%= f.label(:option_id, @option_name1, value: @option1.id)  %></p>
                    <!--<p><=@option1.name_opt%></p>-->
                </div>
            <% end %>
            <% if @option2 %>
                <div class="modal_menu_option">
                    <%= f.radio_button(:option_id, @option2.id) %>
                    <p><%= f.label(:option_id, @option_name2, value: @option2.id)  %></p>
                </div>
            <% end %>
            <% if @option3 %>
                <div class="modal_menu_option">
                    <%= f.radio_button(:option_id, @option3.id) %>
                    <p><%= f.label(:option_id, @option_name3, value: @option3.id)  %></p>
                </div>
            <% end %>
        </div>
        <div class="modal_menu_tocart">
            <!--<div class="tocart_button">-->
            <!--    <p>カートへ</p>-->
            <!--</div>-->
            <%= f.submit 'カートへ', class: 'tocart_button' %>
        </div>        
    </div>
    <% end %>
</div>
<div id="modal_close">
        <i class="fas fa-times"></i>
</div>

<!--<script>-->
<!--    $(function(){-->
<!--        $("#modal_close").click(function(){-->
<!--          $(this).hide();-->
<!--          $("#modal_bg").hide();-->
<!--          $("#modal_menu_indiv").hide();-->
<!--        });-->
<!--    })-->
<!--</script>-->
        <!--<a href="#">-->
            <!--<div class="modal_close_bt">-->
            <!--</div>-->
        <!--</a>-->

app/views/orderlist/modal.js.erb
<!--$("#modal-test").html("<2%='test' %>")-->

<!--$("#modal").html("<2%=j(render @model%>")-->

app/views/orderlist/order_create.html.erb
成功しました

app/views/orderlist/set_menu.html.erb
<div class="menu_background-color">
    <div class="menu_background">
        <header class="menu_header clearfix">
            <div class="menu_header_left">
                <div class="menu_button orange">
                    <a href="/order/top">
                        <p>トップへ</p>
                    </a>
                </div>
            </div>
            <div class="menu_button_right">
                <div class="menu_button orange">
                    <a href="#">
                        <p>会計</p>
                    </a>
                </div>
                <div class="menu_button orange">
                    <a href="#">
                        <p>呼出</p>
                    </a>
                </div>
                <div class="menu_button orange">
                    <a href="#">
                    <!--↑ここ多分link_toを使わないといけないと思う-->
                        <p>未注文</p>
                    </a>
                </div>
                <div class="menu_button orange">
                    <a href="#">
                        <p>注文済</p>
                    </a>
                </div>
            </div>
        </header>
        <div class="menu_category">
                <div class="menu_button orange">
                    <a href="#">
                        <p>セット</p>
                    </a>
                </div>
                <div class="menu_button">
                    <a href="/order/alacarte_menu">
                        <p>一品料理</p>
                    </a>
                </div>
                <div class="menu_button">
                    <a href="/order/noodle_menu">
                        <p>麺類</p>
                    </a>
                </div>
                <div class="menu_button">
                    <a href="/order/rice_menu">
                        <p>ご飯類</p>
                    </a>
                </div>
                <div class="menu_button">
                    <a href="/order/dessert_menu">
                        <p>デザート</p>
                    </a>
                </div>
                <div class="menu_button">
                    <a href="/order/drink_menu">
                        <p>ドリンク</p>
                    </a>
                </div>
        </div>
        <div class="line">
            <h2></h2>
        </div>
        <!--セットメニューに関わる部分-->
        <div class="menu_category2">
            <ul>
                <li id="category11" class="selected">
                    <p>ボリューム</p>
                </li>
                <li id="category12">
                    <p class="double">ランチ・<br>おすすめ</p>
                </li>
                <li id="category13">
                    <p>ユニーク</p>
                </li>
            </ul>
        </div>
        <div class="menu_indiv clearfix">
            <div class="category11">
                <% @menus1.each do |menu| %>
                    <div class="menu_indiv_block" menuid=<%= menu.id %>>
                        <div class="menu_indiv_block2">
                            <!--<2%= link_to (order_indiv_url(menu.id)) do %>-->
                            <!--<2%= link_to (order_indiv_url(menu.id)), remote: true do %>-->
                                <img src=<%= menu.image %> alt="">
                                <div class="menu_indiv_name">
                                    <%= menu.name %>
                                </div>
                                
                            <!--<2%end%>-->
                        </div>
                    </div>
                <% end %>
            </div>
            <div class="category12">
                <% @menus2.each do |menu| %>
                    <div class="menu_indiv_block" menuid=<%= menu.id %>>
                        <!--<2%= link_to (order_indiv_url(menu.id)) do %>-->
                            <div class="menu_indiv_block2">
                                <img src=<%= menu.image %> alt="">
                                <div class="menu_indiv_name">
                                    <%= menu.name %>
                                </div>
                            </div>
                        <!--<2%end%>                            -->
                    </div>
                <% end %>
            </div>
            <div class="category13">
                <% @menus3.each do |menu| %>
                    <div class="menu_indiv_block" menuid=<%= menu.id %>>
                        <!--<2%= link_to (order_indiv_url(menu.id)) do %>-->
                            <div class="menu_indiv_block2">
                                <img src=<%= menu.image %> alt="">
                                <div class="menu_indiv_name">
                                    <%= menu.name %>
                                </div>
                            </div>
                        <!--<2%end%>-->
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

<!--↓井上さんが書いてくれた例-->
<!--<div id='modal'>-->

<!--<input type='button' value='test' id='modal-test' orderid='1'>-->

<!--<script>-->
<!--$('#modal-test').click(function(event) {-->
<!--    var id = $(this).attr('orderid')-->
<!--    var url = '/order/modal_test/' + id-->
<!--    console.log(id)-->
<!--    $.ajax({-->
<!--        url: url,-->
        <!--// contentType: 'text/javascript',-->
<!--        success: function(html){-->
<!--            $('#modal').html(html)-->
<!--        }-->
<!--    })-->
<!--})-->
<!--</script>-->

<!--<script>-->
<!--$(function(){-->
<!--  $("li").on("click", function() {-->
<!--    $("li.selected").removeClass("selected");-->
<!--    $(this).addClass("selected");-->
<!--    $(".menu_indiv").children().hide();-->
<!--    $("."+this.id).show();-->
<!--  });  -->
<!--});-->
<!--</script>-->

app/views/orderlist/top_page.html.erb
<div class="top_page_background">
    <div class="top_page_contents">
        <div class="top_page_nav_n_title">
            <div class="top_page_nav">
                <button class="top_page_nav_button" id="nav_button">
                    <i class="fas fa-bars"><span></span></i>
                </button>
                <div class="top_page_nav_div" id="nav_button2">
                    <ul class="top_page_nav_ul">
                        <li class="top_page_nav_li"><a href="#">ログアウト</a></li>
                        <!--↑delete　を使うからlink toに書き換える必要があるかも-->
                        <li class="top_page_nav_li"><a href="#">中国語</a></li>
                        <li class="top_page_nav_li"><a href="#">English</a></li>
                    </ul>
                </div>
            </div>
            <div class="top_page_title">
                <p>ご来店ありがとうございます！</p>
            </div>
        </div>
        <div class="top_page_menu">
            <div class="top_page_menu_upper clearfix">
                <ul>
                    <li class="top_page_menu_indiv">
                        <a href="/order/recommend_menu">
                            <p>おすすめ</p>
                        </a>
                    </li>
                    <li class="top_page_menu_indiv">
                        <a href="/order/alacarte_menu">
                            <p>一品料理</p>
                        </a>
                    </li>
                    <li class="top_page_menu_indiv">
                        <a href="/order/noodle_menu">
                            <p>麺類</p>
                        </a>
                    </li>
                    <li class="top_page_menu_indiv">
                        <a href="/order/set_menu">
                            <p>セット</p>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="top_page_menu_lower clearfix">
                <ul>
                    <li class="top_page_menu_indiv">
                        <a href="/order/search">
                            <p>検索</p>
                        </a>
                    </li>
                    <li class="top_page_menu_indiv">
                        <a href="/order/dessert_menu">
                            <p class="second">デザート<br>
                            スープ</p>
                        </a>
                    </li>
                    <li class="top_page_menu_indiv">
                        <a href="/order/rice_menu">
                            <p class="second">ご飯<br>
                            定食</p>
                        </a>
                    </li>
                    <li class="top_page_menu_indiv">
                        <a href="/order/drink_menu">
                            <p class="second">ドリンク<br>
                            アルコール</p>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<!--<script>-->
<!--$(function(){-->
<!--	$("#nav_button").click(function(){-->
<!--		$("#nav_button2").slideToggle();-->
<!--	});-->
<!--});-->
<!--</script>-->